name: "Feature Request"
description: "Request a feature or enhancement"
labels: ["feature request"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thank you for creating a feature request 🥳!
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your request in one or two sentences."
    validations:
      required: true
  - type: "dropdown"
    id: "identification"
    attributes:
      label: In relation to...
      description: What part of the codebase are you having an issue with?
      options:
        - API route (/pages/api/*)
        - A page route (/pages/*)
        - A component
        - Styling
        - Vercel
        - Other
    validations:
      required: true
  - type: "textarea"
    id: "justification"
    attributes:
      label: "Justification"
      description: |
        Please provide valid reason(s) why this should be added the website
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed Solution"
      description: |
       If you have any thoughts on how to implement this idea, please note them down!
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        Additional resources (links, screenshots, etc.).
        
